### PR TITLE
Created main content

### LINKED ISSUE #2: Create section and article

### PR DESCRIPTION
**Pull request by adekimpianna**
it consists of section and article. title has been added too.

### CODE REVIEW

**Review by miroslavveljanoski — COMMENTED** [review]
This seems ok for me. If it's ok for @harunaltunhr he can merge it to the master

**Comment by adekimpianna** [comment]
you can do it too @miroslavveljanoski because I made you as the reviewer and the assignee too like Harun 😄

**Comment by miroslavveljanoski** [comment]
@adekimpianna I know that I can do it, but I thought that it's a good practice if every collaborator review the new changes and after that, we can merge it :smile:

**Comment by snicoll** [comment]
For the record, a review from everyone is not strictly necessary. 

Some explanations on "reviewers" and "assignees". The former represents those who should have a look to the code and provide feedback. The latter represents who is in charge of actually merging the proposal.

**Pull request merged**
