### PR TITLE
Created and styled elements closes #1

### LINKED ISSUE #1: Create Header, navbar and footer

### PR DESCRIPTION
**Pull request by harunaltunhr**
@adekimpianna Could you please look at? How is it looks?

### CODE REVIEW

**Review by adekimpianna — COMMENTED** [review]
it looks good, but there is a conflict between master and the new branch from you. I will resolve it! 👍

**Comment by snicoll** [comment]
@harunaltunhr if you put `Closes #1` on the same line as the title it will not close the issue. Remember, a commit message is a title followed by an empty line and then the description (optional). The last line of the description can have an instruction to tell GitHub to reference and/or close the issue when it's merged to `master`.

**Comment by snicoll** [comment]
@adekimpianna while resolving the conflict you could also have amended the commit message to add the extra line. Once you've the PR locally and fixed the conflict you can run `git commit --amend` to polish the commit message.

**Comment by miroslavveljanoski** [comment]
> @adekimpianna while resolving the conflict you could also have amended the commit message to add the extra line. Once you've the PR locally and fixed the conflict you can run `git commit --amend` to polish the commit message.

@snicoll I don't understand this part with `git commit --amend` :confused:

**Comment by adekimpianna** [comment]
@miroslavveljanoski me neither, we will ask @snicoll later in the small group discussion 😄

**Pull request merged**
