### PR TITLE
created main content (from harun file)

### LINKED ISSUE #2: Create section and article

### PR DESCRIPTION
**Pull request by adekimpianna**
created main content: section and article from harun file. guys @miroslavveljanoski @harunaltunhr you can choose which pull request to merge.

### CODE REVIEW

**Review by harunaltunhr — APPROVED** [review]
I liked that title

**Comment by adekimpianna** [comment]
@harun, according to @miroslavveljanoski you should merge this pull request because this one is from your own file.

**Review by miroslavveljanoski — COMMENTED** [review]
It seems great to me :smile:

**Comment by adekimpianna** [comment]
@harunaltunhr @miroslavveljanoski i think we should talk here instead of on Slack. The other people get notifications from our disscussion 😄

**Pull request merged**
